version: '3.4'
services:
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1025:25"
      - "1080:80"
  docs:
    build: ./docs
    volumes:
      - ./laravel/storage/docs:/srv/docs

  php-fpm:
    restart: "no"

  mysql:
    restart: "no"

  caddy:
    restart: "no"
