version: '3.4'
services:
  php-fpm:
    build: ./php-fpm
    restart: always
    env_file:
      - laravel/.env
      - php-fpm/.env
    volumes:
      - ./laravel:/srv/caddy/html

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - mysql/.env
    ports:
      - 3306:3306
    volumes:
      - ${BASE_DATA_DIR:-/srv/prilov}/mysql/datadir:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d

  caddy:
    build: ./caddy
    restart: always
    env_file:
      - caddy/.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${BASE_DATA_DIR:-/srv/prilov}/caddy:/srv/caddy/.caddy
      - ${BASE_DATA_DIR:-/srv/prilov}/ssl:/srv/caddy/ssl
      - ./laravel:/srv/caddy/html
