version: '3.4'
services:
  php-fpm:
    build: ./php-fpm
    restart: always
    env_file:
      - php-fpm/.env
    volumes:
      - ./laravel:/srv/caddy/html:cached

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - mysql/.env
    ports:
      - 3306:3306
    volumes:
      - ${BASE_DATA_DIR:-/srv/prilov}/mysql/datadir:/var/lib/mysql:cached
      - ./mysql/conf.d:/etc/mysql/conf.d:cached

  caddy:
    build: ./caddy
    restart: always
    env_file:
      - caddy/.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${BASE_DATA_DIR:-/srv/prilov}/caddy:/root/.caddy:cached
      - ${BASE_DATA_DIR:-/srv/prilov}/ssl:/srv/certs:cached
      - ./caddy/conf:/srv/caddy:cached
      - ./laravel:/srv/caddy/html:cached
